module.exports = [{
	"name":"consulting",
	"title":"IT Consulting",
	"subtitle":"We do IT Consulting",
	"description":"<p>Bacon ipsum dolor amet turducken brisket filet mignon meatloaf, chuck pancetta flank ham sausage strip steak chicken. Alcatra turducken chicken, beef ribs pancetta hamburger pork. Sirloin chicken chuck capicola. Landjaeger salami brisket, venison ribeye pork strip steak kielbasa pork loin rump pig andouille. Brisket ribeye corned beef salami jerky ground round sausage porchetta beef shoulder capicola biltong.</p>"+
									"<p>Kielbasa t-bone cupim, jowl sausage shankle fatback prosciutto andouille pig bacon. Bacon t-bone cow spare ribs cupim venison. Ground round cow shankle, frankfurter sausage pork filet mignon capicola jowl. Cupim pork belly ham hock turkey. Prosciutto flank picanha pork jowl alcatra kielbasa filet mignon pork belly. Chuck sirloin drumstick ham hock corned beef beef ribs kielbasa capicola jowl. Jerky fatback strip steak, beef bresaola ribeye venison turducken rump shank sausage brisket shoulder boudin.</p>"+
									"<p>Short ribs bresaola hamburger capicola pancetta tail alcatra pork belly. Boudin short loin bresaola kevin, salami pastrami leberkas venison filet mignon cow jowl meatloaf shoulder kielbasa. Capicola pork chop ground round tail cupim kevin turkey boudin bresaola. Spare ribs doner pig frankfurter. Picanha pancetta meatball tongue rump, drumstick cupim.</p>"+
									"<p>Bresaola landjaeger rump pancetta, bacon kevin pig shank pork chop sausage meatball jowl tenderloin ham. Shoulder turkey frankfurter ribeye cupim, beef ribs ham hock shank brisket sausage swine tail ground round landjaeger strip steak. Porchetta bacon chicken t-bone brisket shankle. Pancetta leberkas short ribs jowl capicola turkey alcatra doner porchetta. Salami tri-tip bacon spare ribs prosciutto cupim hamburger chicken pork belly turducken pancetta short ribs sirloin andouille sausage. Kevin venison sirloin kielbasa strip steak shoulder biltong pork chop jerky prosciutto shankle ham hock.</p>"+
									"<p>Bacon filet mignon shank, cupim turkey shankle ball tip fatback short loin shoulder. Short ribs turducken chicken picanha, kielbasa shoulder drumstick t-bone tail corned beef beef ribs pork chop ham andouille brisket. Rump kielbasa shankle chuck shoulder pork loin. Spare ribs chicken ball tip ribeye, ham cupim andouille jowl beef pork belly leberkas. Meatball jerky shoulder sausage t-bone porchetta corned beef picanha chuck jowl shank ground round tri-tip.</p>",
	"layout":"text"
},
{
	"name":"software_development",
	"title":"Software Development",
	"subtitle":"We do Software Development",
	"description":"<p>Bacon ipsum dolor amet turducken brisket filet mignon meatloaf, chuck pancetta flank ham sausage strip steak chicken. Alcatra turducken chicken, beef ribs pancetta hamburger pork. Sirloin chicken chuck capicola. Landjaeger salami brisket, venison ribeye pork strip steak kielbasa pork loin rump pig andouille. Brisket ribeye corned beef salami jerky ground round sausage porchetta beef shoulder capicola biltong.</p>"+
									"<p>Kielbasa t-bone cupim, jowl sausage shankle fatback prosciutto andouille pig bacon. Bacon t-bone cow spare ribs cupim venison. Ground round cow shankle, frankfurter sausage pork filet mignon capicola jowl. Cupim pork belly ham hock turkey. Prosciutto flank picanha pork jowl alcatra kielbasa filet mignon pork belly. Chuck sirloin drumstick ham hock corned beef beef ribs kielbasa capicola jowl. Jerky fatback strip steak, beef bresaola ribeye venison turducken rump shank sausage brisket shoulder boudin.</p>"+
									"<p>Short ribs bresaola hamburger capicola pancetta tail alcatra pork belly. Boudin short loin bresaola kevin, salami pastrami leberkas venison filet mignon cow jowl meatloaf shoulder kielbasa. Capicola pork chop ground round tail cupim kevin turkey boudin bresaola. Spare ribs doner pig frankfurter. Picanha pancetta meatball tongue rump, drumstick cupim.</p>"+
									"<p>Bresaola landjaeger rump pancetta, bacon kevin pig shank pork chop sausage meatball jowl tenderloin ham. Shoulder turkey frankfurter ribeye cupim, beef ribs ham hock shank brisket sausage swine tail ground round landjaeger strip steak. Porchetta bacon chicken t-bone brisket shankle. Pancetta leberkas short ribs jowl capicola turkey alcatra doner porchetta. Salami tri-tip bacon spare ribs prosciutto cupim hamburger chicken pork belly turducken pancetta short ribs sirloin andouille sausage. Kevin venison sirloin kielbasa strip steak shoulder biltong pork chop jerky prosciutto shankle ham hock.</p>"+
									"<p>Bacon filet mignon shank, cupim turkey shankle ball tip fatback short loin shoulder. Short ribs turducken chicken picanha, kielbasa shoulder drumstick t-bone tail corned beef beef ribs pork chop ham andouille brisket. Rump kielbasa shankle chuck shoulder pork loin. Spare ribs chicken ball tip ribeye, ham cupim andouille jowl beef pork belly leberkas. Meatball jerky shoulder sausage t-bone porchetta corned beef picanha chuck jowl shank ground round tri-tip.</p>",
	"image":{"src":"http://placehold.it/350x350"},
	"layout":"text-image"
}
];